<docs>
	<doc for="ApplicationException.ApplicationException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ApplicationException"/> 
class with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name="context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during
      deserialization to reconstitute the exception object transmitted over a stream.
      For more information, see <see topic="cpconSerialization"/>.</para>
		</remarks>
		<seealso topic="cpconSerialization"/>
	</doc><doc for="ApplicationException.ApplicationException">
		<overload>
			<para>Initializes a new instance of the
   <see cref="System.ApplicationException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.ApplicationException"/> class.</para>
		</summary>
		<remarks>
			<para>This constructor initializes the <see cref="System.Exception.Message"/>
property of the new instance to a system-supplied message that describes the
error, such as "An application error has occurred." This message takes into
account the current system culture.</para>
			<para>The following table shows the initial property
   values for an instance of <see cref="System.ApplicationException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>A
   null reference (<see langword="Nothing"/> in Visual Basic).</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ApplicationException.ApplicationException1">
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.ApplicationException"/> class
      with a specified error message.</para>
		</summary>
		<param name="message">A message that describes the error.</param>
		<remarks>
			<para>The content of the <paramref name="message"/> parameter is intended to be understood by humans. The caller of
   this constructor is required to ensure that this string has been localized for
   the current system culture.</para>
			<para>This message takes into account the current system culture. </para>
			<para>The following table shows the initial property
   values for an instance of <see cref="System.ApplicationException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>A
   null reference (<see langword="Nothing"/> in Visual Basic).</description>
				</item>
				<item>
					<term><see langword="Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ApplicationException.ApplicationException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ApplicationException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not a null reference, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>The content of the <paramref name="message"/> parameter is intended to be
   understood by humans. The caller of this constructor is required to ensure
   that this string has been localized for the current
   system culture. </para>
			<para>An exception that is thrown as a direct result of a
   previous exception should include a reference to the previous exception in
   the <see cref="System.Exception.InnerException"/> property. The
<see cref="System.Exception.InnerException"/> property returns 
   the same value that is passed into the constructor, or a null
   reference if the <see cref="System.Exception.InnerException"/> property does not
   supply the inner exception value to the constructor. </para>
			<para>The following table shows the initial property values
   for an instance of <see cref="System.ApplicationException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="ApplicationException">
		<summary>
			<para>The exception that is thrown when a
      non-fatal application error occurs.</para>
		</summary>
		<remarks>
			<para><see cref="System.ApplicationException"/> is thrown by a user program,
   not by the common language runtime. If you are designing an application that
   needs to create its own exceptions, derive from the <see cref="System.ApplicationException"/>
   class. <see cref="System.ApplicationException"/> extends <see cref="System.Exception"/>, but does not add new functionality. This exception is
   provided as means to differentiate between exceptions defined by applications versus exceptions defined by the
   system.</para>
			<para><see cref="System.ApplicationException"/>does not provide information as to the cause of the exception.
In most scenarios, instances of this class should not be thrown. In cases where
this class is instantiated, a human-readable message describing the error should
be passed to the constructor.</para>
			<para><see cref="System.ApplicationException"/> uses the HRESULT COR_E_APPLICATION, which has the
value 0x80131600.</para>
			<para>For a list of initial property values for an instance of <see cref="System.ApplicationException"/>,
see the <see cref="System.ApplicationException"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
