<docs>
	<doc for="DuplicateWaitObjectException.DuplicateWaitObjectException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.DuplicateWaitObjectException"/> class with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name="context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to
      reconstitute the exception object transmitted over a stream. For more
      information, see <see topic="cpconSerialization"/>.</para>
		</remarks>
		<seealso topic="cpconSerialization"/>
	</doc><doc for="DuplicateWaitObjectException.DuplicateWaitObjectException">
		<overload>
			<para>Initializes a new instance of the
   <see cref="System.DuplicateWaitObjectException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.DuplicateWaitObjectException"/> class.</para>
		</summary>
		<remarks>
			<para>This constructor initializes the <see cref="System.Exception.Message"/> 
property of the new instance to a system-supplied message that describes the
error, such as "Duplicate objects in argument." This message takes into account
the current system culture.</para>
			<para>The following table shows the initial property
   values for an instance of <see cref="System.DuplicateWaitObjectException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>A 
   null reference (<see langword="Nothing"/> in Visual Basic).</description>
				</item>
				<item>
					<term><see cref="System.ArgumentException.Message"/></term>
					<description>The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="DuplicateWaitObjectException.DuplicateWaitObjectException2">
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.DuplicateWaitObjectException"/> class with a
      specified error message and the name of
      the parameter that causes this exception.</para>
		</summary>
		<param name="parameterName">The name of the parameter that caused the exception.</param>
		<param name="message">The message that describes the error.</param>
		<remarks>
			<para>The content of the <paramref name="parameterName"/> and 
<paramref name="message"/> parameters is intended to be understood by humans. The caller 
   of this constructor is required to ensure
   that these strings have been localized for the current
   system culture.</para>
			<para>An exception that is thrown as a direct result of a previous exception should 
   include a reference to the previous exception in the <see cref="System.Exception.InnerException"/>
   property. The <see cref="System.Exception.InnerException"/> property returns
   the same value that is passed into the constructor, or a null reference
   (<see langword="Nothing"/> in Visual Basic) if the <see cref="System.Exception.InnerException"/>
   property does not supply the inner exception value to the constructor. </para>
			<para>The following table shows the initial property values for an instance of
<see cref="System.DuplicateWaitObjectException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>A 
   null reference (<see langword="Nothing"/> in Visual Basic)</description>
				</item>
				<item>
					<term><see cref="System.ArgumentException.Message"/></term>
					<description>The error message string.</description>
				</item>
				<item>
					<term><see cref="System.ArgumentException.ParamName"/></term>
					<description>The parameter name string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="DuplicateWaitObjectException.DuplicateWaitObjectException1">
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.DuplicateWaitObjectException"/> class with the name
      of the parameter that causes this exception.</para>
		</summary>
		<param name="parameterName">The name of the parameter that caused the exception.</param>
		<remarks>
			<para>The content of <paramref name="parameterName"/> is intended to be
   understood by humans.</para>
			<para>The following table shows the initial property
   values for an instance of <see cref="System.DuplicateWaitObjectException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>A 
   null reference (<see langword="Nothing"/> in Visual Basic).</description>
				</item>
				<item>
					<term><see cref="System.ArgumentException.Message"/></term>
					<description> The localized error message string.</description>
				</item>
				<item>
					<term><see cref="System.ArgumentException.ParamName"/></term>
					<description>The parameter name string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="DuplicateWaitObjectException">
		<summary>
			<para>The exception that is thrown when an object appears more
      than once in an array of synchronization objects.</para>
		</summary>
		<remarks>
			<para>The common language runtime provides a thread
      synchronization mechanism based on synchronization objects waiting for
      execution in an array of <see cref="System.Threading.WaitHandle"/> objects. If the array
      of <see cref="System.Threading.WaitHandle"/> objects passed to <see cref="System.Threading.WaitHandle.WaitAll"/> or
   <see cref="System.Threading.WaitHandle.WaitAny"/> contains
      any duplicate operating system handles, <see cref="System.DuplicateWaitObjectException"/> is thrown. For more
      information, see <see cref="System.Threading.WaitHandle"/>.</para>
			<para><see cref="System.DuplicateWaitObjectException"/> uses the HRESULT
   COR_E_DUPLICATEWAITOBJECT, which has the value 0x80131529.</para>
			<para>For a list of initial property values for an instance of <see cref="System.DuplicateWaitObjectException"/>, see
the <see cref="System.DuplicateWaitObjectException()"/> constructors.</para>
		</remarks>
		<seealso cref="System.Threading.WaitHandle"/>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconThreading"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
