<docs>
	<doc for="UnauthorizedAccessException.UnauthorizedAccessException3">
		<summary>
			<para>
            Initializes a new instance of the 
            <see cref="System.UnauthorizedAccessException"/>
             class with serialized
 data.
         </para>
		</summary>
		<param name="info">
         The 
         <see cref="System.Runtime.Serialization.SerializationInfo"/>
          that holds the serialized object data about the exception being thrown.
      </param>
		<param name="context">
         The 
         <see cref="System.Runtime.Serialization.StreamingContext"/>
          that contains contextual information about the source or destination.
      </param>
	</doc>
	<doc for="UnauthorizedAccessException.UnauthorizedAccessException">
		<overload>
			<para> Initializes a new instance of the
   <see cref="System.UnauthorizedAccessException"/>
   class.
   </para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.UnauthorizedAccessException"/> class.</para>
		</summary>
		<remarks>
			<para>This constructor initializes the <see cref="System.Exception.Message"/> property of the new instance 
   to a system-supplied message that describes the error, such as "Attempted to
   perform an unauthorized operation." This message takes into account the current
   system culture. </para>
			<para>The following table shows the initial property values for an instance of 
<see cref="System.MemberAccessException"/>.</para>
			<list type="table">
					<listheader>
						<term>Property</term>
						<description>Value</description>
					</listheader>
					<item>
						<term><see cref="System.Exception.InnerException"/></term>
						<description>A null reference (<see langword="Nothing"/> 
in Visual Basic).</description>
					</item>
					<item>
						<term><see cref="System.Exception.Message"/></term>
						<description>The localized error message 
   string.</description>
					</item>
				</list>
		</remarks>
	</doc><doc for="UnauthorizedAccessException.UnauthorizedAccessException1">
		<summary>
			<para> Initializes a new instance of the
   <see cref="System.UnauthorizedAccessException"/>
   class with a specified error
   message.
   </para>
		</summary>
		<param name="message"> The message that describes the error.</param>
		<remarks>
			<para>The content of the <paramref name="message"/> parameter should be understandable to 
   the user. The caller of this constructor is required to ensure that this string
   has been localized for the current system culture. </para>
			<para>The following table shows the initial property values for an instance of 
<see cref="System.UnauthorizedAccessException"/>. </para>
			<list type="table">
					<listheader>
						<term>Property</term>
						<description>Value</description>
					</listheader>
					<item>
						<term><see cref="System.Exception.InnerException"/></term>
						<description>A null reference (<see langword="Nothing"/> 
in Visual Basic).</description>
					</item>
					<item>
						<term><see cref="System.Exception.Message"/></term>
						<description>The error message 
   string.</description>
					</item>
				</list>
		</remarks>
	</doc><doc for="UnauthorizedAccessException.UnauthorizedAccessException2">
		<summary>
			<para> Initializes a new instance of the
   <see cref="System.UnauthorizedAccessException"/>
   
   class with a specified error message and a reference to the
   inner exception that is the cause of this exception.
   </para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not a null reference (<see langword="Nothing"/> in Visual Basic), the current exception is raised in a<see langword="catch"/>block that handles the inner exception.</param>
		<remarks>
			<para> An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the
   <see cref="System.Exception.InnerException"/>
   property. The
   
<see cref="System.Exception.InnerException"/> property returns 
   the same value that is passed into the constructor, or a null reference
   (<see langword="Nothing"/> in Visual Basic)
   if the
<see cref="System.Exception.InnerException"/>
property does not supply the inner exception value to
the constructor.</para>
			<para> The following table shows the initial property values for an instance of
<see cref="System.UnauthorizedAccessException"/>
.</para>
			<list type="table">
				<listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term>
						<see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term>
						<see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="UnauthorizedAccessException">
		<summary>
			<para>The exception that is thrown when the operating
      system denies access because of an I/O error or a specific
      type of security error.</para>
		</summary>
		<remarks>
			<para><see langword="UnauthorizedAccessException "/>
uses the HRESULT
COR_E_UNAUTHORIZEDACCESS, which has the value 0x80070005.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
