<docs>
	<doc for="CustomAttributeFormatException.CustomAttributeFormatException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.CustomAttributeFormatException"/> class with the 
   specified serialization and context information.</para>
		</summary>
		<param name="info">The data for serializing or deserializing the custom attribute.</param>
		<param name=" context">The source and destination for the custom attribute.</param>
	</doc><doc for="CustomAttributeFormatException">
		<summary>
			<para> The exception that is
      thrown when the binary format of a custom attribute is invalid.</para>
		</summary>
		<remarks>
			<para><see langword="CustomAttributeFormatException"/> uses the HRESULT COR_E_FORMAT
   which has the value 0x80131537.</para>
			<para><see langword="CustomAttributeFormatException"/>
is thrown if a custom
attribute on a data type is formatted incorrectly, possibly because of a bug
in the tool used to create the data type.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso cref="System.FormatException"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="CustomAttributeFormatException.CustomAttributeFormatException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Reflection.CustomAttributeFormatException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.CustomAttributeFormatException"/>
class with the default properties.</para>
		</summary>
		<remarks>
   This constructor initializes an instance of
<see langword="CustomAttributeFormatException"/> with an empty message string and
   the root cause exception set to <see langword="null"/>.
   
   <para>This constructor sets the properties of the
   <see langword="Exception"/>
   object as follows:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>null</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The
   empty string ("").</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="CustomAttributeFormatException.CustomAttributeFormatException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.CustomAttributeFormatException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Reflection.CustomAttributeFormatException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The <paramref name="inner"/> exception.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
	<doc for="CustomAttributeFormatException.CustomAttributeFormatException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.CustomAttributeFormatException"/> class with the specified message.</para>
		</summary>
		<param name="message">The message that indicates the reason this exception was thrown.</param>
		<remarks>
			<para>This
      constructor sets the properties of the Exception object as follows:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/></description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso cref="System.FormatException"/>
	</doc>
</docs>
