<docs>
	<doc for="TargetParameterCountException.TargetParameterCountException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetParameterCountException"/>
class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.Reflection.TargetParameterCountException"/> class
      with an empty message string and the root cause of the exception.</para>
		</summary>
		<remarks>
			<see langword="TargetParameterCountException"/> inherits from <see cref="System.Exception"/> . This constructor sets the 
   properties of the Exception object as shown in the following table.
   <list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/></description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The empty string ("").</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="TargetParameterCountException.TargetParameterCountException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetParameterCountException"/>
class with its message string set to the given message
and the root cause exception.</para>
		</summary>
		<param name="message">A <see langword="String"/> describing the reason this exception was thrown.</param>
		<remarks>
			<para><see langword="TargetParmeterCountException"/> inherits from <see cref="System.Exception"/>. This constructor sets the 
   properties of the <see langword="Exception "/>
   object as shown in
   the following table.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/></description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="TargetParameterCountException.TargetParameterCountException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetParameterCountException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Reflection.TargetParameterCountException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="TargetParameterCountException">
		<summary>
			<para> The exception that is thrown when the number of parameters for an invocation does not match the number expected. This class
      cannot be inherited.</para>
		</summary>
		<remarks>
			<para><see langword="TargetParameterCountException"/> uses the HRESULT
   COR_E_TARGETPARAMCOUNT which has the value 0x8002000E.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
