<docs>
	<doc for="IsolatedStorageException.IsolatedStorageException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/> class.</para>
		</overload>
		<summary>
			<para> Initializes a new instance of the <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/> class with default properties.
   </para>
		</summary>
		<remarks>
			<para>The following table shows the initial property values 
      for an instance of <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="IsolatedStorageException.IsolatedStorageException1">
		<summary>
			<para> Initializes a new instance of the <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/> class with a specified error
   message.
   </para>
		</summary>
		<param name="message">The error message that explains the reason for the exception. </param>
		<remarks>
			<para>The following table shows the initial property values 
      for an instance of <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="IsolatedStorageException.IsolatedStorageException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/> 
class with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data. </param>
		<param name=" context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to reconstitute the 
      exception object transmitted over a stream. For more information, see
   <see topic="cpconserialization"/>.</para>
		</remarks>
	</doc><doc for="IsolatedStorageException.IsolatedStorageException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.IO.IsolatedStorage.IsolatedStorageException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="IsolatedStorageException">
		<summary>
			<para> The exception that is thrown when an operation in isolated storage fails.</para>
		</summary>
		<remarks>
			<para><see langword="IsolatedStorageException "/> uses the ISS_E_ISOSTORE, which has the value 0x80131450.
   </para>
			<para>The most common examples of isolated storage exceptions are as follows. </para>
			<list type="bullet"><item>
					<term>
      
      Missing evidence. Isolated storage requires evidence
      (information about the assembly and its origin) in order to determine the
      identity of the code and connect it to the correct associated file space.
      Without this information, isolated storage cannot be used.</term>
				</item>
				<item>
					<term>
      
      Invalid operations. Some <see cref="System.IO.FileStream"/> operations are not supported for
      isolated storage.</term>
				</item>
			</list>
			<para>For a list of initial property values for an instance of
<see langword="IsolatedStorageException"/>, see the <see cref="M:System.IO.IsolatedStorage.IsolatedStorageException.#ctor"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
