<docs>
	<doc for="FileLoadException">
		<summary>
			<para> The exception that is thrown when a managed assembly is found
      but cannot be loaded.</para>
		</summary>
		<remarks>
			<para>Represents the error that occurs when a <see cref="System.Reflection.Assembly"/> file is found but
   cannot be loaded.</para>
			<para>The <see cref="System.IO.FileNotFoundException"/> exception is thrown when the file fails to load
because it cannot be located. If the file is located, but cannot be loaded due
to insufficient permissions, a <see cref="System.Security.SecurityException"/> is thrown.</para>
			<para><see langword="FileLoadException"/> has
the default HRESULT of COR_E_FILELOAD, which has the value 0x80131621, but this is not the
only possible HRESULT.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileLoadException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/> class, setting the
<see cref="System.Exception.Message"/> property of the new instance to a system-supplied 
   message that describes the error, such as "Could not load the specified file."
   This message takes into account the current system culture.</para>
		</summary>
		<remarks>
			<para>The
   <see cref="System.Exception.InnerException"/> property and
   <see cref="System.IO.FileLoadException.FileName"/> property of the new instance are
      initialized to <see langword="null"/>.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileLoadException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/>
class with the specified error message.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<remarks>
			<para>This
      constructor initializes the <see cref="System.IO.FileLoadException.Message"/> property
      of the new instance using <paramref name="message"/>. The <see cref="System.Exception.InnerException"/> property and
   <see cref="System.IO.FileLoadException.FileName"/> property of the new instance are
      initialized to <see langword="null"/>.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileLoadException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see langword="InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see langword="InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.IO.FileLoadException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.IO.FileLoadException.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
For
more information on inner exceptions, see
<see cref="System.Exception.InnerException"/>.
</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileLoadException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/> class with a specified error message and the name of
   the file that could not be loaded.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<param name="fileName">A <see cref="System.String"/> containing the name of the file that was not loaded.</param>
		<remarks>
			<para>This
      constructor initializes the <see cref="System.IO.FileLoadException.Message"/> property
      of the new instance using <paramref name="message"/> and the
      <see cref="System.IO.FileLoadException.FileName"/> property using <paramref name="fileName"/>. The <see cref="System.Exception.InnerException"/> property of the new instance
      is initialized to <see langword="null"/>.</para>
			<para><see cref="System.IO.FileLoadException.FileName"/> is not required to be a file stored on disk; it can
   be any part of a system that supports access to streams. For example, depending on
   the system, this class might be able to access a physical device.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileLoadException4">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/> class with a specified error message, the name of
   the file that could not be loaded, and a reference to the inner exception
   that is the cause of this exception.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<param name=" fileName">A <see cref="System.String"/> containing the name of the file that was not loaded.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
      <see langword="InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see langword="InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para><see cref="System.IO.FileLoadException.FileName"/> is not required to be a file stored on disk; it can
be any part of a system that supports access to streams. For example, depending on
the system, this class might be able to access a physical device.</para>
			<para>The following table shows the initial property values for an instance of <see cref="System.IO.FileLoadException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.IO.FileLoadException.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
For
more information on inner exceptions, see
<see cref="System.Exception.InnerException"/>.
</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.Message">
		<summary>
			<para> Gets the error message and
      the name of the file that caused this exception.</para>
		</summary>
		<value>
			<para>A string containing the error message and the name of the file that caused
      this exception.</para>
		</value>
		<remarks>
			<para>This
      property overrides <see cref="System.Exception.Message"/>.</para>
			<para>If no message was supplied to the constructor for the current exception, this
      property returns a system-supplied error message. If the <see cref="System.IO.FileLoadException.FileName"/>
      property is not a null reference, the message includes the file name,
      for example, "Unable to load file a <paramref name="FileName"/>." (a <paramref name="FileName"/>
      represents the value returned by <see cref="System.IO.FileLoadException.FileName"/>.)
      If <see cref="System.IO.FileLoadException.FileName"/> is <see langword="null"/>, this is indicated
      in the system-supplied message as "(null)". The system-supplied message takes
      into account the current system culture.</para>
			<para>This property is read-only.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileName">
		<summary>
			<para>Gets the name of the file that causes this exception.</para>
		</summary>
		<value>
			<para>A <see cref="System.String"/>
containing the name of the file with the invalid image, or a null reference if
no file name was passed to the constructor for the current instance.</para>
		</value>
		<remarks>
			<para>This property returns the name of the file supplied to the constructor for
      the current instance, if any. If the file name was not specified or is a null
      reference, this property returns a null reference. </para>
			<para>This property is read-only. </para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.ToString">
		<summary>
			<para>Returns the fully qualified name of the current exception, and
      possibly the error message, the name of the inner exception, and the stack trace.</para>
		</summary>
		<returns>
			<para>A string containing the fully qualified name of this
      exception, and possibly the error message, the name of the inner exception, and
      the stack trace, depending on which <see cref="System.IO.FileLoadException"/>
      constructor is used.</para>
		</returns>
		<remarks>
			<para>This
      method overrides <see cref="System.Object.ToString"/>.</para>
			<para>The string representation returned by this method includes the name of the
      exception, the value of the <see cref="System.IO.FileLoadException.Message"/>the value of the <see cref="System.IO.FileLoadException.FileName"/> property, and the result of calling
   <see cref="System.Environment.StackTrace"/> . If any of these members is a null
      reference, its value is not included in the returned string.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FileLoadException5">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileLoadException"/>
class with serialized data.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		<remarks>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.FusionLog">
		<summary>
			<para> Gets the log file that describes why an assembly
      load failed.</para>
		</summary>
		<value>
			<para>A string containing errors reported by the assembly cache.</para>
		</value>
		<exception cref="System.Security.SecurityException">The caller does not have the required permission.</exception>
		<permission cref="System.Security.Permissions.SecurityPermission">to provide evidence and view and modify policy. Associated enumerations: <see cref="System.Security.Permissions.SecurityPermissionFlag.ControlEvidence" qualify="true"/>, <see cref="System.Security.Permissions.SecurityPermissionFlag.ControlPolicy" qualify="true"/>.</permission>
		<seealso topic="cpgrffusionlogviewerfuslogvwexe"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileLoadException.GetObjectData">
		<summary>
			<para>Sets the <see cref="System.Runtime.Serialization.SerializationInfo"/> with
   the file name and additional exception information.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		<exception cref="System.Security.SecurityException">The caller does not have the required permission.</exception>
		<permission cref="System.Security.Permissions.SecurityPermission">to provide evidence and view and modify policy. Associated enumerations: <see cref="System.Security.Permissions.SecurityPermissionFlag.ControlEvidence" qualify="true"/>, <see cref="System.Security.Permissions.SecurityPermissionFlag.ControlPolicy" qualify="true"/>.</permission>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
</docs>
