<docs>
   <doc for="ThreadStopException">
 <summary>
    <para>
       Represents an exception that is thrown into a thread to cause it
       to stop.
    </para>
 </summary>
 <remarks>
    <para>
       Typically, the <see langword='ThreadStopException '/>
       is an
       exception that is not caught, and the thread dies as a result. All of its
       members are private.
    </para>
    <para>
       This is
       thrown by the virtual machine and should NOT be thrown by any user
       thread. It is useless to subclass this.
    </para>
    <para>
       When handling an exception, it is sometimes helpful to
       have a reference to the exception(s) that caused the error to occur. You can use
       this constructor to create a chain of new and more meaningful exceptions with
       the <see cref='System.Exception.InnerException'/> property
       set to the inner exception reference. This more meaningful exception can then
       be thrown to the caller. Note that with this functionality it is possible to
       create a series of linked exceptions that terminates with the exception that
       was first thrown. (See <see cref='System.Exception'/> for more
       information.)
    </para>
    <para>
       ThreadStopException inherits from the <see cref='System.Exception'/>
       class. The properties of the Exception object as
       follows:
    </para>
    <list type='table'>
       <listheader>
          <term>
             Property Type
          </term>
          <description>
             Condition
          </description>
       </listheader>
       <item>
          <term>
          <see cref='System.Exception.InnerException'/>
       </term>
       <description>
       <see langword='null'/>
       .
    </description>
 </item>
 <item>
    <term>
    <see cref='System.Exception.Message'/>
 </term>
 <description>
    The empty string.
 </description>
 </item>
 </list>
 </remarks>
   </doc>
</docs>

