<docs>
	<doc for="ThreadStateException.ThreadStateException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Threading.ThreadStateException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Threading.ThreadStateException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="ThreadStateException.ThreadStateException">
		<overload>
			<para> Initializes a new instance of the <see cref="System.Threading.ThreadStateException"/>
class.</para>
		</overload>
		<summary>
			<para> Initializes a new instance of the <see cref="System.Threading.ThreadStateException"/> class
   with default properties.</para>
		</summary>
		<remarks>
			<para>This constructor initializes the <see langword="Message"/> 
property of the new instance to a system-supplied message that describes the
error, such as "The requested operation cannot be performed on the thread due to
its current state." This message takes into account the current system
culture.</para>
			<para>The following table shows the initial property values for an instance of
<see cref="System.Threading.ThreadStateException"/>.</para>
			<list type="table">
				<listheader>
					<term> Property</term>
					<description> Value </description>
				</listheader>
				<item>
					<term>
						<see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term>
						<see cref="System.Exception.Message"/></term>
					<description> The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="ThreadStateException.ThreadStateException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Threading.ThreadStateException"/> class with serialized data.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to reconstitute the
      exception object transmitted over a stream. For more information, see
   <see topic="cpconSerialization"/>.</para>
		</remarks>
		<seealso topic="cpconSerialization"/>
	</doc><doc for="ThreadStateException.ThreadStateException1">
		<summary>
			<para> Initializes a new instance of the <see cref="System.Threading.ThreadStateException"/> class with
   a specified error message.</para>
		</summary>
		<param name="message"> The error message that explains the reason for the exception. </param>
		<remarks>
			<para>This constructor initializes the <see langword="Message "/>property of the new instance using the
<paramref name="message"/> parameter.</para>
			<para>The following table shows the initial property values for an instance of
<see cref="System.Threading.ThreadStateException"/>.</para>
			<list type="table">
				<listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term>
						<see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term>
						<see cref="System.Exception.Message"/></term>
					<description> The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="ThreadStateException">
		<summary>
			<para> The exception that is thrown when a <see cref="System.Threading.Thread"/> is in an invalid <see cref="System.Threading.Thread.ThreadState"/>
for the method call.</para>
		</summary>
		<remarks>
			<para>Once a thread is created, it is in at least one of
      the <see cref="System.Threading.ThreadState"/>
      states until it terminates. <see langword="ThreadStateException"/> is thrown by methods
      that cannot perform the requested operation due to the current state of a thread. For example, trying to restart
      an aborted thread by calling <see cref="System.Threading.Thread.Start"/> on a thread that has terminated throws a <see cref="System.Threading.ThreadStateException"/>.</para>
			<para><see cref="System.Threading.ThreadStateException"/> uses the HRESULT COR_E_THREADSTATE, which has
   the value 0x80131520.</para>
			<para>For a list of initial property values for an instance of <see cref="System.Threading.ThreadStateException"/>, see 
the <see cref="M:System.Threading.ThreadStateException.#ctor"/> constructors.</para>
		</remarks>
		<example>
			<para>The following example demonstrates an error that causes the system to throw a
   <see langword="ThreadStateException"/> .</para>
			<codelink SampleID="ThreadStEx" SnippetID="1"/>
			<para>This code produces the following output:</para>
			<code>
In main. Attempting to restart myThread. 
    Working thread... 
    Caught: Thread is running or terminated. Cannot restart.
</code>
		</example>
		<seealso cref="System.Threading.Thread"/>
		<seealso cref="System.Threading.ThreadState"/>
		<seealso topic="cpconManagedUnmanagedThreading"/>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
